apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce